Add team page
openproblems-bio/website pull request #16
Opened 2022-08-02 00:07 UTC by dburkhardt

2022-08-03 15:34 UTC, scottgigante reviewed
It's a bit weird that team members are listed alphabetical by first name, but it's a bit unclear to me if it's possible to fix that with this widget

2022-08-03 15:34 UTC, scottgigante commented on config/_default/menus.yaml
> +  - name: Team
I would put team before join

2022-08-04 22:56 UTC, jbloom22 requested changes
I don't think I'm authorized to PR, edits in comments below.

2022-08-04 22:56 UTC, jbloom22 commented on content/authors/jonathan_b/_index.md
> +role: Purposefully Unemployed; Formerly Cellarity and Broad Institute
Purposefully Unemployed; formerly Cellarity, Broad Institute, MIT

2022-08-04 22:56 UTC, jbloom22 commented on content/authors/jonathan_b/_index.md
> +    link: 'mailto:johnny@appleseed.com'
jonathan.bloom.cv@gmail.com

2022-08-04 22:56 UTC, jbloom22 commented on content/authors/jonathan_b/_index.md
> +    link: https://www.linkedin.com/in/johnny-appleseed/
https://www.linkedin.com/in/jon-bloom/

2022-08-04 22:56 UTC, jbloom22 commented on content/authors/jonathan_b/_index.md
> +    link: https://github.com/johnnyappleseed
https://github.com/jbloom22

2022-08-04 22:56 UTC, jbloom22 commented on content/authors/jonathan_b/_index.md
> +    link: https://twitter.com/johnnyappleseed
https://twitter.com/MorseCell

2022-08-04 22:56 UTC, jbloom22 commented on content/authors/jonathan_b/_index.md
> +title: Jonathan Bloom, PhD
Jonathan M. Bloom, PhD

2022-08-12 18:23 UTC, merged