add new external link filter
openproblems-bio/website pull request #179
Opened 2023-03-12 22:17 UTC by KaiWaldrant

## Describe your changes

## Issue ticket number and link
Closes #xxxx (Replace xxxx with the GitHub issue number)

## Checklist before requesting a review
- [ x] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [x ] Minor changes
  - [ ] Bug fixes

- [ ] Proposed changes are described in the CHANGELOG.md

- [ ] CI Preview succeeds and looks good!

2023-03-12 22:37 UTC, KaiWaldrant commented
It is fixed for the benchmark cards but the bibliography links are not fixed

2023-03-13 08:22 UTC, KaiWaldrant commented
the biblio ref links are opening in a new tab on the released website too #180

2023-03-13 08:42 UTC, KaiWaldrant commented
#180 is intentional so the PR can be reviewed

2023-03-13 13:46 UTC, rcannood requested changes

2023-03-13 13:46 UTC, rcannood commented on CHANGELOG.md
> +* use filter to determine external link
Can you document this as a bug fix?

```suggestion
## BUG FIXES

* Fix internal links being treated as external links in PR previews (#179).
```

2023-03-13 14:23 UTC, rcannood commented
Is it possible `link-external-newwindow: true` shouldn't be removed? None of the links on the main page have target blank.

2023-03-13 14:24 UTC, rcannood reviewed
Is it possible `link-external-newwindow: true` shouldn't be removed? None of the links on the main page have target blank.

2023-03-13 15:13 UTC, KaiWaldrant commented
you are totally correct. forgot to test the external links ofcourse ...
I also added the external link icon.

2023-03-13 15:25 UTC, KaiWaldrant commented
hmm the results card are not fixed now :|

2023-03-13 18:16 UTC, scottgigante-immunai commented
Do we want to keep `link-external-icon: true`? I could go either way on this. Also, looks like navbar docs links still don't open in new tab.

2023-03-13 20:28 UTC, KaiWaldrant commented
the alternative regex seems to fit the bill.
Wanted to add the icons to see what it looked like. I'm either way, maybe it is not necessary as the links will open in a new window anyway.

2023-03-14 08:52 UTC, rcannood commented
> Also, looks like navbar docs links still don't open in new tab.

It's really strange that the links in the navbar indeed don't open in a new tab.

2023-03-14 09:00 UTC, rcannood commented
Looks like this is a feature that was added to quarto 1.3. I opened a separate PR for this (#188).

2023-03-14 09:01 UTC, rcannood approved these changes

2023-03-14 09:01 UTC, merged