update to quarto 1.3
openproblems-bio/website pull request #221
Opened 2023-04-21 09:52 UTC by KaiWaldrant

## Describe your changes
update to quarto v1.3

## Issue ticket number and link
Closes #196 

## Checklist before requesting a review
- [x] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [x] Minor changes
  - [ ] Bug fixes

- [x] Proposed changes are described in the CHANGELOG.md

- [x] CI Preview succeeds and looks good!

2023-04-21 11:13 UTC, rcannood commented
Just to make sure, do not merge this PR yet.

The preview does not look OK yet. Waiting for quarto-dev/quarto-cli#5257 to make it in a pre-release candidate.

2023-04-27 07:33 UTC, KaiWaldrant commented
Quarto 1.3 has finally been released

2023-04-27 14:01 UTC, scottgigante-immunai requested changes
@KaiWaldrant 

> - [X] I have performed a self-review of my code
> - [ ] CI Preview succeeds and looks good!

The deploy preview does not in fact succeed. Please re-request the review once tests are passing.

2023-04-27 19:23 UTC, scottgigante-immunai approved these changes

2023-04-28 14:10 UTC, merged