Docs/v2/edits
openproblems-bio/website pull request #222
Opened 2023-04-21 11:06 UTC by mumichae

## Describe your changes
Minor edits on v2 documenation

## Checklist before requesting a review
- [x] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [x] Minor changes
  - [ ] Bug fixes

- [ ] Proposed changes are described in the CHANGELOG.md

- [ ] CI Preview succeeds and looks good!

2023-04-21 11:10 UTC, rcannood requested changes

2023-04-21 11:10 UTC, rcannood commented on documentation/contribute/add_a_dataset.qmd
> +For more parameter options, refer to @sec-parameters
Incomplete sentence

2023-04-21 11:10 UTC, rcannood commented on documentation/contribute/add_a_method.qmd
> +### 1. Imports and libraries
There is already a step 1, step 2, step 3, .... Would it make sense to use a. b. c. here?

2023-04-25 11:17 UTC, rcannood commented on documentation/contribute/add_a_method.qmd
> +| `functionality.info.reporsitory_url`         | The repository url for the method.
Just spotted a typo

```suggestion
| `functionality.info.repository_url`         | The repository url for the method.                                                                                                                                                                                                                                                                         |
```

2023-04-27 09:53 UTC, KaiWaldrant requested changes

2023-04-27 09:53 UTC, KaiWaldrant commented on documentation/contribute/add_a_dataset.qmd
> +For more parameter options, refer to @sec-parameters.
this causes the website to show `section ...` this has no meaning to the reader. I would suggest to just add a link.
```suggestion
For more parameter options, refer to [Parameters](#parameters) section.
```

2023-04-27 09:53 UTC, KaiWaldrant commented on documentation/contribute/add_a_dataset.qmd
> +The script must ensure that that the output anndata object has the format as described in @sec-format.
same applies for this
```suggestion
The script must ensure that that the output anndata object has the format as described in the [format](#format-of-a-raw-dataset-object) section.

```

2023-04-27 09:53 UTC, KaiWaldrant commented on documentation/contribute/add_a_dataset.qmd
> +## Parameters {#sec-parameters}
Not needed if changes are accepted.
```suggestion
## Parameters
```

2023-04-27 09:53 UTC, KaiWaldrant commented on documentation/contribute/add_a_dataset.qmd
> +## Format of a raw dataset object {#sec-format}
same

```suggestion
## Format of a raw dataset object
```

2023-04-27 09:53 UTC, KaiWaldrant commented on documentation/contribute/add_a_method.qmd
> +| `__merge__`                                  | The file specified in this field contains information regarding the input and output arguments of the component, as well as a unit test to ensure that
Not a big fan of the full table. shouldn't we do the same for the other files ?
```suggestion
#### `functionality.name`

A unique identifier for the method. Must be written in snake case. Example: `my_new_method`.

#### `functionality.info`

Please edit this section in the config file to fill in the necessary metadata.

| Metadata field                               | Description                                                                                                                                                                                                                                                                                                |
|----------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `pretty_name`             | A label for the method used for visualisations and documentation. Example:  `"My new method"` .                                                                                                                                                                                                            |
| `summary`                 | A one sentence summary of the method. Used for creating short overviews of the components in a task.                                                                                                                                                                                                       |
| `description`             | An explanation for how the method works. Used for creating reference documentation of a task.                                                                                                                                                                                                              |
| `reference`               | A bibtex reference key to the paper where the method is described.                                                                                                                                                                                                                                         |
| `documentation_url`       | The url to the documentation of the method.                                                                                                                                                                                                                                                                |
| `repository_url`         | The repository url for the method.                                                                                                                                                                                                                                                                         |
| `preferred_normalization` | Which normalization method a component _prefers_. Possible values are  `r norm_methods_str` . Each value corresponds to a normalization component in the directory [ `src/datasets/normalization` ]( https://github.com/openproblems-bio/openproblems-v2/tree/main/src/datasets/normalization ).           |


#### `__merge__`

The file specified in this field contains information regarding the input and output arguments of the component, as well as a unit test to ensure that the component is functioning properly. Normally you don't need to change this if you gave the right arguments to the `create_component` component.
```

2023-04-27 09:53 UTC, KaiWaldrant commented on documentation/contribute/add_a_method.qmd
> +Note that both `anndata~=0.8` and `pyyaml` are necessary Python package dependencies.
```suggestion
Note that both `anndata~=0.8.0` and `pyyaml` are necessary Python package dependencies.
```

2023-05-04 12:34 UTC, rcannood commented
I much prefer to look at the table when the page is wide enough, but on mobile the table looks quite bad. I'll revert the tabular changes for now.

2023-05-04 12:36 UTC, rcannood approved these changes

2023-05-04 13:30 UTC, KaiWaldrant approved these changes

2023-05-04 14:10 UTC, merged