Fix/thumnail typo v2
openproblems-bio/website pull request #232
Opened 2023-04-28 20:33 UTC by KaiWaldrant

## Describe your changes
Revert intentional typo in `thumbnail` it has been fixed in quarto v1.3

## Checklist before requesting a review
- [x] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [x] Minor changes
  - [ ] Bug fixes

- [x] Proposed changes are described in the CHANGELOG.md

- [ ] CI Preview succeeds and looks good!

2023-04-28 20:34 UTC, KaiWaldrant commented
Replaces #161. Too many issue due to being transferred from old repo.

2023-04-30 22:31 UTC, scottgigante-immunai requested changes

2023-04-30 22:31 UTC, scottgigante-immunai commented on competitions/neurips_2021_docs/data/index.qmd
> +css: ../docs.css
Can you add this change to the changelog?

2023-05-02 14:38 UTC, scottgigante-immunai commented on CHANGELOG.md
> +* add `../docs.css` to neurips 2022 documentation to activate the `.thumbnail-image` change (#232)
Change was to `neurips_2021_docs`, is this a typo?
```suggestion
* add `../docs.css` to neurips 2021 documentation to activate the `.thumbnail-image` change (#232)
```

2023-05-02 19:26 UTC, rcannood approved these changes

2023-05-02 19:26 UTC, merged