add base image reference to doc
openproblems-bio/website pull request #282
Opened 2023-07-06 08:58 UTC by KaiWaldrant

## Describe your changes
reference the base image in add dependencies section of the `create_component` pages

## Issue ticket number and link
Closes #281

## Checklist before requesting a review
- [x] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [x] Minor changes
  - [ ] Bug fixes

- [ ] Proposed changes are described in the CHANGELOG.md

- [ ] CI Preview succeeds and looks good!

2023-07-06 14:52 UTC, rcannood requested changes
Great work! Just one minor idea

2023-07-06 14:52 UTC, rcannood commented on documentation/create_component/_include/_add_dependencies.qmd
> +setup:
Could you also add 

```
platforms:
  - type: docker
    Image: your custom image
```

2023-07-07 07:12 UTC, KaiWaldrant commented on documentation/create_component/_include/_add_dependencies.qmd
> +setup:
updated

2023-07-07 17:49 UTC, rcannood approved these changes

2023-07-07 17:49 UTC, merged