Add resource info to task results
openproblems-bio/website pull request #309
Opened 2024-02-14 16:52 UTC by rcannood

## Describe your changes

## Issue ticket number and link
Closes #xxxx (Replace xxxx with the GitHub issue number)

## Checklist before requesting a review
- [ ] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Bug fixes

- [ ] Proposed changes are described in the CHANGELOG.md

- [ ] CI Preview succeeds and looks good!

2024-02-14 21:44 UTC, KaiWaldrant requested changes
Is it possible to change the font type of the error legend for the dark mode ? 
![image](https://github.com/openproblems-bio/website/assets/80908902/f7055204-75b2-46c2-946e-5e2f148ce162)

2024-02-14 21:45 UTC, KaiWaldrant commented
It looks great, nice way of visualising!

2024-02-15 04:38 UTC, rcannood commented
We'll have to wait for this PR to be merged.

Since we're merging into another PR, we could already merge this PR, though. WDYT?

2024-02-15 08:38 UTC, KaiWaldrant approved these changes

2024-02-15 09:31 UTC, merged