Create pred_mod page
openproblems-bio/website pull request #320
Opened 2024-02-19 13:12 UTC by KaiWaldrant

## Describe your changes

## Issue ticket number and link
Closes #xxxx (Replace xxxx with the GitHub issue number)

## Checklist before requesting a review
- [ ] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Bug fixes

- [ ] Proposed changes are described in the CHANGELOG.md

- [ ] CI Preview succeeds and looks good!

2024-02-21 09:36 UTC, rcannood commented
* There are join warnings in the rendered page:
      Warning in inner_join(results %>% select(method_id, dataset_id, metric_values) %>% : Detected an unexpected many-to-many relationship between `x` and `y`.
      ℹ Row 33 of `x` matches multiple rows in `y`.
      ℹ Row 38 of `y` matches multiple rows in `x`.
      ℹ If a many-to-many relationship is expected, set `relationship =
        "many-to-many"` to silence this warning.
  Is openproblems-bio/openproblems-v2#381 a fix for this?

* The names of the NeurIPS2021 datasets are too long:
  ![Screenshot from 2024-02-21 10-31-49](https://github.com/openproblems-bio/website/assets/553642/1e9ee5ba-9ec8-4b17-94b7-feecad49eb0d)

  @dburkhardt What about changing the names to `OP-NeurIPS2021 Multiome` and `OP-NeurIPS2021 CITE-Seq` ? or `OpenProblems 2021 Multiome` and `OpenProblems 2021 CITE-Seq`?

2024-02-21 09:38 UTC, rcannood requested changes
* There are join warnings in the rendered page:
      Warning in inner_join(results %>% select(method_id, dataset_id, metric_values) %>% : Detected an unexpected many-to-many relationship between `x` and `y`.
      ℹ Row 33 of `x` matches multiple rows in `y`.
      ℹ Row 38 of `y` matches multiple rows in `x`.
      ℹ If a many-to-many relationship is expected, set `relationship =
        "many-to-many"` to silence this warning.
  Is openproblems-bio/openproblems-v2#381 a fix for this?

* The names of the NeurIPS2021 datasets are too long:
  ![Screenshot from 2024-02-21 10-31-49](https://github.com/openproblems-bio/website/assets/553642/1e9ee5ba-9ec8-4b17-94b7-feecad49eb0d)

  @dburkhardt What about changing the names to `OP-NeurIPS2021 Multiome` and `OP-NeurIPS2021 CITE-Seq` ? or `OpenProblems 2021 Multiome` and `OpenProblems 2021 CITE-Seq`?

* Seems like NewWave+ KNNR is always failing. Can you look into why this is the case?

2024-02-21 09:42 UTC, KaiWaldrant commented
Yes, the PR in OPv2 is a fix for this PR that's why I didn't send it for review yet :).

2024-02-21 09:53 UTC, rcannood commented
Oic! My bad ;)

2024-02-21 14:48 UTC, KaiWaldrant commented
And the failing of `newwave+knnr` is due to out of disk storage:
```
Error: An error has occurred in allocating shared memory:
No space left on device
```

2024-02-24 08:26 UTC, rcannood commented
> And the failing of `newwave+knnr` is due to out of disk storage:
> 
> ```
> Error: An error has occurred in allocating shared memory:
> No space left on device
> ```

Can we then give it some more disk space? :relaxed:

2024-02-27 09:18 UTC, KaiWaldrant commented
Adding disk space worked but there seems to be an issue with bioconductor which is giving the method an error. Requires more investigation but I would suggest already merge this PR and update when the issue is fixed.

2024-02-27 11:37 UTC, rcannood commented
Glad to see that the dataset info is fixed!

Right now, the results only contain very simple methods -- KNN, RF and LM. I'd like to see some other methods included before publishing the results, e.g. guanlab_dengkw_pm, NewWave+KNNR, Novel.

2025-01-07 19:25 UTC, rcannood approved these changes
LGTM!

2025-01-07 19:25 UTC, merged